# Generated by Django 3.0.2 on 2020-02-02 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('personal_page', models.BooleanField()),
                ('public', models.BooleanField(default=True)),
                ('admins', models.ManyToManyField(related_name='pages', to='accounting.Account')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.Account')),
            ],
        ),
    ]
