# Generated by Django 3.0.2 on 2020-02-02 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20200202_1900'),
        ('paging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_id',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Account'),
        ),
    ]
