# Generated by Django 3.0.2 on 2020-02-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'verbose_name': 'توییت'},
        ),
        migrations.AddField(
            model_name='tweet',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
