# Generated by Django 3.0.2 on 2020-02-01 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0001_initial'),
        ('accounting', '0007_delete_student'),
        ('twitting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={},
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='is_root',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='likers',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_followers',
        ),
        migrations.AddField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='author', to='accounting.Account', verbose_name='author'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paging.Page'),
        ),
    ]
