# Generated by Django 3.0.2 on 2020-02-02 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20200202_1900'),
        ('twitting', '0002_auto_20200202_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributors', to='accounting.Account'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='parent_tweet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='twitting.Tweet'),
        ),
    ]
