# Generated by Django 3.0.3 on 2020-03-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitting', '0003_auto_20200202_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={},
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='contributors',
        ),
        migrations.AddField(
            model_name='tweet',
            name='last_like_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='plain_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
