# Generated by Django 3.0.3 on 2020-03-08 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_auto_20200308_1604'),
        ('twitting', '0004_auto_20200308_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_follower', 'New Follower'), ('new_like', 'New Like'), ('new_post', 'New Post')], max_length=20)),
                ('seen', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounting.Account')),
                ('tweet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweet_alert', to='twitting.Tweet')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_alerts', to='accounting.Account')),
            ],
        ),
    ]
