# Generated by Django 3.0.3 on 2020-03-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20200202_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='account',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='account',
            name='profile_photo',
            field=models.FileField(default='/profiles/default.png', null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
