# Generated by Django 3.0.2 on 2020-01-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20200131_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(default='nothing until now', max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.TextField(default='iran!', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='portfolio_site',
            field=models.URLField(blank=True, default='google.com', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
