# Generated by Django 3.0.2 on 2020-02-01 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
