# Generated by Django 3.0.2 on 2020-02-01 22:43

from django.db import migrations, models
import django.db.models.deletion
import paging.models


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0001_initial'),
        ('accounting', '0009_auto_20200201_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='personal_page',
            field=models.ForeignKey(default=paging.models.Page, on_delete=django.db.models.deletion.PROTECT, to='paging.Page'),
        ),
    ]
