# Generated by Django 3.0.2 on 2020-02-01 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0001_initial'),
        ('accounting', '0011_auto_20200201_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='personal_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paging.Page'),
        ),
    ]
