# Generated by Django 3.0.3 on 2020-03-08 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0003_page_description'),
        ('accounting', '0003_auto_20200308_1604'),
        ('following', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paging.Page')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
            ],
        ),
    ]
